import streamlit as st
import numpy as np
from PIL import Image
import joblib

# ------------------------------------
# Page Configuration
# ------------------------------------
st.set_page_config(
    page_title="Gender Detection AI",
    page_icon="🧑",
    layout="centered"
)

# ------------------------------------
# Custom CSS
# ------------------------------------
st.markdown("""
<style>
.main {
    background-color: #f5f7fa;
}

.title{
    text-align:center;
    color:#4B0082;
    font-size:42px;
    font-weight:bold;
}

.subtitle{
    text-align:center;
    font-size:18px;
    color:gray;
}

.prediction{
    font-size:28px;
    text-align:center;
    font-weight:bold;
    color:#0B5394;
}

.footer{
    text-align:center;
    color:gray;
    margin-top:40px;
}
</style>
""", unsafe_allow_html=True)

# ------------------------------------
# Load Model
# ------------------------------------
model = joblib.load("gender_model.pkl")

IMG_SIZE = 64

# ------------------------------------
# Header
# ------------------------------------
st.markdown('<p class="title">🧑 Gender Detection using Machine Learning</p>',
            unsafe_allow_html=True)

st.markdown('<p class="subtitle">Upload a face image and the model will predict whether the person is Male or Female.</p>',
            unsafe_allow_html=True)

st.divider()

# ------------------------------------
# Upload Image
# ------------------------------------
uploaded_file = st.file_uploader(
    "📂 Upload an Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    col1, col2 = st.columns([1,1])

    with col1:
        st.image(image, caption="Uploaded Image", use_container_width=True)

    # Image Preprocessing
    resized = image.resize((IMG_SIZE, IMG_SIZE))
    resized = np.array(resized)
    resized = resized.flatten()

    # Prediction
    prediction = model.predict([resized])[0]
    probability = model.predict_proba([resized])[0]

    with col2:

        st.subheader("Prediction Result")

        if prediction == 0:
            st.success("👩 Female")
        else:
            st.success("👨 Male")

        st.write("### Confidence")

        st.write(f"👩 Female : **{probability[0]*100:.2f}%**")
        st.progress(float(probability[0]))

        st.write(f"👨 Male : **{probability[1]*100:.2f}%**")
        st.progress(float(probability[1]))

    st.divider()

    st.info(
        "⚠️ This prediction is generated by a Machine Learning model and may not always be accurate."
    )

else:
    st.info("👆 Please upload an image to begin prediction.")

st.markdown(
    '<div class="footer">Made with ❤️ using Streamlit & Scikit-learn</div>',
    unsafe_allow_html=True
)